name: GitHub Actions

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🚀 Workflow triggered by a ${{ github.event_name }} event on branch ${{ github.ref }}"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Verify Maven installation
        run: mvn -v

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

      - name: Run unit tests
        run: mvn -B test
